### ISSUE TITLE
multipleVariantPValue function stopped working and Error in sort.int

### ISSUE THREAD

**Issue by klmartinez** [sherman5/RVS#4]
I was able to successfully run RVS and the `multipleVariantPValue `function on a set of 2 exome families a few days ago. 

Yesterday I tried running the same script and received the following errors:

```
> resultB <- multipleVariantPValue(fam27_28$genotypes, fam27_28$fam, sharingProbs, filter='bonferroni', alpha=0.05) 
Error in sort.int(x, na.last = na.last, decreasing = decreasing, ...) : 'x' must be atomic 
> traceback() 
5: stop("'x' must be atomic") 
4: sort.int(x, na.last = na.last, decreasing = decreasing, ...) 
3: sort.default(unname(pot_pvals)) 
2: sort(unname(pot_pvals)) 
1: multipleVariantPValue(fam27_28$genotypes, fam27_28$fam, sharingProbs, filter = "bonferroni", alpha = 0.05)
```
My inputs haven't changed so I am not sure what I am doing wrong. My understanding of the error is that one of the inputs isn't formatted correctly, but this was all running successfully only a few days ago. The only inconsistency is that my version of RVS stopped working, and I had to re-install the updated "sherman5/RVS" version. What could I be doing wrong?

**Comment by sherman5** [comment]
We haven't changed RVS recently, but a new version of Bioconductor came out a month ago, as well as a new version of R (3.6.0). My only guess is one of these version changes affected a dependency in RVS. As of now, we're still seeing clean builds - so I'm not sure what exactly the problem was. Is everything working ok now that you reinstalled?

**Comment by klmartinez** [comment]
I am having the same error after re-installing. I can try re-installing the older versions of Bioconductor and R.

**Comment by klmartinez** [comment]
R 3.6.0
RVS 1.5.4
BiocManager 1.30.4

**Comment by klmartinez** [comment]
One new thing I did notice is that instead of using BiocManager::install("sherman5/RVS") to install RVS, I have to now install using remotes::install_github("sherman5/RVS")...

**Comment by klmartinez** [comment]
I forgot to update with the solution: 
In order to run RVS you have to use the following versions:
R 3.5.2
RVS 1.5.4
BiocManager 3.8
